spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    cat.itacademy.s04.t02.n02.drinkcardmoa: INFO
    org.springframework.security: WARN
