spring:
  application:
    name: festival-drinks

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  secret: ${JWT_SECRET}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:1440}

app:
  payment:
    frontend-success-url: ${PAYMENT_FRONTEND_SUCCESS_URL}

sumup:
  base-url: ${SUMUP_BASE_URL}
  api-key: ${SUMUP_API_KEY}
  merchant-code: ${SUMUP_MERCHANT_CODE}

logging:
  level:
    cat.itacademy.s04.t02.n02.drinkcardmoa: INFO
    org.springframework.security: WARN
