package cat.itacademy.s04.t02.n02.drinkcardmoa.drinkcard.application.port.in.dto.command;

public record CreatePaymentCheckoutCommand(
        String volunteerId,
        String redirectUrl,
        String idempotencyKey // generated By the frontend
) {
}
